# https://docs.travis-ci.com/user/customizing-the-build/

sudo: required

install: true
services:
  - docker


before_script:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - docker build -t langrisha/room:bikeshed ./bikeshed
  - docker build -t langrisha/room:polyglot ./polyglot
  - docker build -t langrisha/room:laputa ./laputa
  - docker build -t langrisha/room:latest .

after_success:
  - docker push langrisha/room:bikeshed
  - docker push langrisha/room:polyglot
  - docker push langrisha/room:laputa
  - docker push langrisha/room:latest
