sudo: required
install: true
services:
  - docker

before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

script:
- |
    set -e
    docker build -t langrisha/room:bikeshed ./bikeshed
    docker build -t langrisha/room:polyglot ./polyglot
    docker build -t langrisha/room:decapitated ./decapitated
    docker build -t langrisha/room:laputa ./laputa
    docker build -t langrisha/room:latest .

after_success:
- |
    if ([ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ]) &&
        [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
        docker push langrisha/room:bikeshed
        docker push langrisha/room:polyglot
        docker push langrisha/room:decapitated
        docker push langrisha/room:laputa
        docker push langrisha/room:latest
    fi
