#!/bin/bash
# See: https://github.com/mark-adams/docker-chromium-xvfb

_kill_procs() {
    kill -TERM $chromium
    wait $chromium
    kill -TERM $xvfb
}

# Setup termination traps and relay the signal to the child processes.
trap _kill_procs SIGTERM

# Start Xvfb
Xvfb :99 $XVFB_ARGS &
xvfb=$!

export DISPLAY=:99

chromium --no-sandbox $@ &
chromium=$!

wait $chromium
wait $xvfb
